repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.6
    hooks:
    -   id: clang-format
        name: Formating C files with Clang-Format
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: Formating Python files with Black
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        name: Running a static code analysis
        args:
            - "--std=c89"
            - "--suppress=missingInclude"
            - "--suppress=unmatchedSuppression"
            - "--suppress=missingIncludeSystem"
            - "--suppress=unusedFunction"
